cache:
  paths:
    - node_modules/

install_deps:
  stage: prepare
  script:
    - yarn
  only:
    refs:
      - merge_requests
      - develop
      - main

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist
    reports:
      dotenv: .env
  only:
    refs:
      - merge_requests
      - develop
      - main

deploy:
  stage: deploy
  script:
    - firebase deploy --only hosting ---project "$FIREBASE_PROJECT" --token "$FIREBASE_TOKEN"
  dependencies:
    - build
  only:
    refs:
      - develop
      - main

deploy_mr:
  stage: deploy
  script:
    - firebase hosting:channel:deploy $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME --expires 7d --project "$FIREBASE_PROJECT" --token "$FIREBASE_TOKEN"
  dependencies:
    - build
  only:
    - merge_requests

stages:
  - prepare
  - build
  - deploy
