export const CAREER_JOURNEY_DATA = [
  {
    title: "vvvv",
    description: "vvvv",
    from: "2022-11-29",
    to: null,
    isArchive: true,
    isCurrent: true,
    icon: "cricket",
  },
  {
    title: "Ggggh",
    description: "",
    from: "2012-01-24",
    to: "2022-02-20",
    isArchive: true,
    isCurrent: false,
    icon: "flag",
  },
  {
    title: "Hhh",
    description: "Uu",
    from: "1991-03-30",
    to: null,
    isArchive: true,
    isCurrent: false,
    icon: "golf",
  },
  {
    title: "Hh",
    description: "Hhhh",
    from: "2021-03-29",
    to: "2021-03-30",
    isArchive: true,
    isCurrent: false,
    icon: "soccer",
  },
  {
    title: "Ghjkkj ghh",
    description: "Ghi kkk",
    from: "1997-10-29",
    to: "2021-10-29",
    isArchive: true,
    isCurrent: false,
    icon: "soccer",
  },
  {
    title: "Phong",
    description: "",
    from: "1980-02-29",
    to: null,
    isArchive: true,
    isCurrent: false,
    icon: "golf",
  },
  {
    title: "My nam is Phong",
    description:
      "Hhh ahhâj dkf nffn fkfk hâhh dpgong jfjffn bxbxxb abb có gò nưav đâu mà ",
    from: "2022-10-30",
    to: "2023-10-30",
    isArchive: true,
    isCurrent: false,
    icon: "medal",
  },
  {
    title: "Hhh",
    description: "Hhh",
    from: "2021-10-30",
    to: null,
    isArchive: true,
    isCurrent: false,
    icon: "soccer",
  },
];
