export const RoutePath = {
  HOME: "/",
  FAN: "/fan",
  FAN_ONBOARDING: "/fan/onboarding",
  ATHLETE: "/athlete",
  ATHLETE_SETUP_ACCOUNT: "/athlete/setup-account",
  ATHLETE_CHECKLIST: "/athlete/checklist",
  ATHLETE_PAGE_INFO: "/athlete/onboarding/page-information",
  ATHLETE_BASIC_INFO: "/athlete/onboarding/page-information",
  ATHLETE_SPORT_PROFILE: "/athlete/onboarding/page-information",
  ATHLETE_CAREER_JOURNEY: "/athlete/onboarding/page-information",
  SIGN_IN: "/sign-in",
  FAN_SIGN_UP: "/fan/sign-up",
  ATHLETE_SIGN_UP: "/athlete/sign-up",
  JOINING_AS: "/joining-as",
  ATHLETE_PROFILE: "/athlete/my-profile",
  FAN_VIEW_ATHLETE_PROFILE: (athleteId: string) =>
    `/fan/athlete-profile/${athleteId}`,
  VERIFY_OTP: "/verify-otp",
};
