import { ReactElement, useEffect } from "react";
import { Box } from "@chakra-ui/react";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { Session } from "next-auth";
import DefaultLayout from "@/layouts/default";
import { useAppDispatch, wrapper } from "@/store";
import { setContext } from "@/libs/axiosInstance";
import { setData } from "@/store/globalSlice";
import HomePageBanner from "@/components/ui/HomePage/HomePageBanner";
import { checkUserRoles } from "@/middleware/checkUserRoles";

const homePageData = {
  title: "For Athletes, By Fans",
  content:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
};
export default function Home() {
  const dispatch = useAppDispatch();
  useEffect(() => {
    dispatch(setData(true));
  });

  const { data: session } = useSession();

  return (
    <Box className="home-page h-full flex flex-col">
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePageBanner
        content={homePageData.content}
        title={homePageData.title}
      />
      {JSON.stringify(session)}
    </Box>
  );
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <DefaultLayout>{page}</DefaultLayout>;
};

export const getServerSideProps = wrapper.getServerSideProps(
  () => (context) => {
    setContext(context);

    return checkUserRoles(context, (session: Session | null) => {
      return {
        props: {
          session,
        },
      };
    });
  }
);
